apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-clusterip
  namespace: case2
spec:
  type: ClusterIP
  selector:
    app: blackbox-exporter-app
  ports:
    - name: blackbox-exporter-port
      port: 9115
      targetPort: 9115
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: case2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter-app
  template:
    metadata:
      labels:
        app: blackbox-exporter-app
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:v0.12.0
        ports:
        - containerPort: 9115
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: blackbox.yml-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox.yml-data
  namespace: case2
data:
  blackbox.yml: |
      icmp:
        prober: icmp
        timeout: 10s
        preferred_ip_protocol: "ip4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: icmp-target
  namespace: case2
data:
  icmp-target.yml: |
    - targets:
        - '192.168.99.100'
