apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: case2
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    nodePort: 30300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: case2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.1.3
        ports:
        - containerPort: 3000
