---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-ne
spec:
  selector:
    matchLabels:
      name: prometheus-ne
  template:
    metadata:
      labels:
        name: prometheus-ne
    spec:
      containers:
        - image: prom/node-exporter:v0.14.0
          name: prometheus-node-exporter
          ports:
            - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-np
spec:
  type: NodePort
  ports:
    - name: prometheus-ne
      port: 9100
      targetPort: 9100
      protocol: TCP
      nodePort: 30080
  selector:
    name: prometheus-ne
