---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-export
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/node-exporter:v0.14.0
          name: prometheus-node-exporter
          ports:
          - name: prom-node-exp
            containerPort: 9100
            hostPort: 9100
      hostNetwork: true
      hostPID: true

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-ne
  labels:
    app: prometheus-ne
  annotations:
    prometheus.io/scrape: 'true'

spec:
  clusterIP: None
  ports:
    - name: prometheus-ne
      port: 9100
      protocol: TCP
  selector:
    app: prometheus
  type: ClusterIP
