apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      protocol: TCP
      name: prometheus
      targetPort: 9090
      nodePort: 30868
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v1.7.0
          args:
            - --config.file=/mnt/etc/prometheus.yml
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/etc/
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    rule_files:
      - "/etc/prometheus-rules/*.rules"
    scrape_configs:

      # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L37
      - job_name: 'kubernetes-nodes'
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:9100'
            target_label: __address__
#    global:
#      scrape_interval:     15s
#      evaluation_interval: 15s
#    scrape_configs:
#      - job_name: kubernetes-nodes
#        scrape_interval: 10s
#        scrape_timeout: 10s
#        metrics_path: /metrics
#        scheme: http
#        kubernetes_sd_configs:
#        - api_server: null
#          role: node
#          namespaces:
#          names: []
#        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#        tls_config:
#          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#          insecure_skip_verify: false
#        relabel_configs:
#        - source_labels: [__address__]
#          separator: ;
#          regex: (.*):10250
#          target_label: __address__
#          replacement: ${1}:9100
#          action: replace
#
